// src/lib/seo.ts
export const defaultSEOConfig = {
  title: 'Saqib Sohail - Full Stack Developer & Software Engineer',
  description:
    'Full stack developer with expertise in React, Next.js, TypeScript, and Node.js. Specializing in building scalable, performant, and accessible web applications with modern best practices.',
  keywords: [
    'Full Stack Developer',
    'Software Engineer',
    'React',
    'Next.js',
    'TypeScript',
    'Node.js',
    'Web Development',
    'Performance Optimization',
    'Web Accessibility',
    'Frontend Development',
    'Backend Development',
    'DevOps',
  ],
  authors: [{ name: 'Saqib Sohail' }],
  creator: 'Saqib Sohail',
  publisher: 'Saqib Sohail',
  generator: 'Next.js',
  applicationName: 'Saqib Sohail - Portfolio',
  referrer: 'origin-when-cross-origin',
  colorScheme: 'dark',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://ssohail.com',
    siteName: 'Saqib Sohail Portfolio',
    title: 'Saqib Sohail - Full Stack Developer & Software Engineer',
    description: 'Full stack developer specializing in React, Next.js, TypeScript, and Node.js. Building innovative, performant web solutions.',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Saqib Sohail - Full Stack Developer',
    description: 'Full stack developer specializing in modern web technologies',
    creator: '@saqibroy',
  },
};
