// Types for contentlayer are generated by Contentlayer
import { allPosts, Post } from 'contentlayer/generated';
import { format } from 'date-fns';
import Layout from '@/components/Layout';
import Image from 'next/image';
import MDXContent from '@/components/MDXContent';
import { Calendar, Clock, User, Tag, ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import AudioSummaryPlayer from "./AudioSummaryPlayer";
import { GiscusComments, SocialShareButtons, LikeButton } from './ClientComponents';

export async function generateStaticParams() {
  return allPosts.map((post: Post) => ({ slug: post.slug }));
}

export async function generateMetadata({ params }: { params: { slug: string } }) {
  const post = allPosts.find((post: Post) => post.slug === params.slug);
  if (!post) return { 
    title: 'Post Not Found', 
    description: 'The requested blog post could not be found.' 
  };

  const title = `${post.title} | Saqib Sohail`;
  const description = post.description || 'Read this article on ssohail.com';
  const url = `https://ssohail.com/blog/${post.slug}`;
  const imageUrl = post.image || `https://ssohail.com/og-image.png`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      url,
      siteName: 'Saqib Sohail',
      images: [
        {
          url: imageUrl,
          width: 1200,
          height: 630,
          alt: post.title,
        },
      ],
      locale: 'en_US',
      type: 'article',
      authors: post.author ? [post.author] : undefined,
      publishedTime: post.date,
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [imageUrl],
      creator: '@ssohail',
      site: '@ssohail',
    },
    alternates: {
      canonical: url,
    },
  };
}

export default function PostPage({
  params,
}: {
  params: { slug: string };
}) {
  const post = allPosts.find((post: Post) => post.slug === params.slug);

  if (!post) {
    return (
      <Layout>
        <div className="min-h-screen flex items-center justify-center">
          <div className="text-center">
            <h1 className="text-4xl font-bold text-white mb-4">Post Not Found</h1>
            <p className="text-gray-400 mb-8">The requested blog post could not be found.</p>
            <Link href="/blog" className="inline-flex items-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors">
              <ArrowLeft className="w-4 h-4" />
              Back to Blog
            </Link>
          </div>
        </div>
      </Layout>
    );
  }

  // Function to get author initials
  const getAuthorInitials = (authorName: string) => {
    return authorName
      .split(' ')
      .map(name => name.charAt(0).toUpperCase())
      .join('');
  };

  // Function to estimate reading time
  const estimateReadingTime = (content: string) => {
    const wordsPerMinute = 200;
    const wordCount = content.split(/\s+/).length;
    const minutes = Math.ceil(wordCount / wordsPerMinute);
    return `${minutes} min read`;
  };

  const currentUrl = `https://ssohail.com/blog/${post.slug}`;

  return (
    <Layout>
      {/* Hero Section */}
      <section className="relative pt-24 pb-16">
        {/* Background Pattern */}
        <div className="absolute inset-0 bg-gradient-to-br from-blue-900/20 via-transparent to-green-900/20 pointer-events-none" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(59,130,246,0.1),transparent)] pointer-events-none" />
        
        <div className="container mx-auto px-4 max-w-6xl relative">
          {/* Breadcrumb */}
          <nav className="flex items-center gap-2 mb-8 text-sm">
            <Link href="/" className="text-gray-400 hover:text-white transition-colors">
              Home
            </Link>
            <span className="text-gray-600">/</span>
            <Link href="/blog" className="text-gray-400 hover:text-white transition-colors">
              Blog
            </Link>
            <span className="text-gray-600">/</span>
            <span className="text-white">{post.title}</span>
          </nav>

          {/* Hero Content */}
          <div className="text-center mb-12">
            <h1 className="text-4xl md:text-6xl lg:text-7xl font-black mb-6 leading-tight">
              <span className="bg-gradient-to-r from-blue-400 via-purple-400 to-green-400 bg-clip-text text-transparent">
                {post.title}
              </span>
            </h1>
            {post.description && (
              <p className="text-xl md:text-2xl text-gray-300 max-w-3xl mx-auto leading-relaxed">
                {post.description}
              </p>
            )}
          </div>

          {/* Meta Information */}
          <div className="flex flex-wrap items-center justify-center gap-6 mb-12 text-gray-400">
            <div className="flex items-center gap-2">
              <Calendar className="w-4 h-4" />
              <time dateTime={post.date}>
                {format(new Date(post.date), 'MMMM d, yyyy')}
              </time>
            </div>
            <div className="flex items-center gap-2">
              <Clock className="w-4 h-4" />
              <span>{estimateReadingTime(post.body.raw)}</span>
            </div>
            {post.author && (
              <div className="flex items-center gap-2">
                <User className="w-4 h-4" />
                <span>{post.author}</span>
              </div>
            )}
          </div>

          {/* Hero Image */}
          <div className="relative aspect-[16/9] w-full rounded-2xl overflow-hidden shadow-2xl mb-12">
            <div className="absolute inset-0 bg-gradient-to-t from-black/50 via-transparent to-transparent z-10" />
            <Image
              src={post.image || `https://placehold.co/1200x500/1a1a1a/ffffff?text=${encodeURIComponent(post.title)}`}
              alt={post.title}
              fill
              className="object-cover object-center"
              priority
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 80vw, 1200px"
            />
          </div>

          {/* Tags */}
          {post.tags && post.tags.length > 0 && (
            <div className="flex flex-wrap justify-center gap-3 mb-16">
              {post.tags.map((tag: string) => (
                <span
                  key={tag}
                  className="group inline-flex items-center gap-2 px-6 py-3 rounded-full text-sm font-medium bg-gray-900/50 text-gray-300 ring-1 ring-gray-700 hover:ring-blue-500 hover:bg-blue-900/20 transition-all duration-300 backdrop-blur-sm"
                >
                  <Tag className="w-3 h-3" />
                  {tag}
                </span>
              ))}
            </div>
          )}

          {/* Audio Summary Section */}
          <div className="my-16">
            <AudioSummaryPlayer postContent={post.body.raw} postTitle={post.title} />
          </div>
        </div>
      </section>

      {/* Article Content */}
      <article className="relative">
        <div className="container mx-auto px-4 max-w-4xl">
          {/* Article Body */}
          <div className="prose prose-invert prose-xl max-w-none prose-headings:font-bold prose-headings:tracking-tight prose-h1:text-4xl prose-h2:text-3xl prose-h3:text-2xl prose-h2:mt-16 prose-h2:mb-8 prose-h3:mt-12 prose-h3:mb-6 prose-p:text-gray-300 prose-p:leading-relaxed prose-p:mb-6 prose-a:text-blue-400 prose-a:no-underline hover:prose-a:underline prose-a:transition-all prose-strong:text-white prose-strong:font-semibold prose-blockquote:border-l-blue-500 prose-blockquote:bg-blue-900/10 prose-blockquote:px-6 prose-blockquote:py-4 prose-blockquote:rounded-r-lg prose-ul:my-8 prose-li:text-gray-300 prose-li:mb-2">
            <MDXContent code={post.body.code} />
          </div>

          {/* Like and Share Section */}
          <div className="mt-16 mb-12 p-6 rounded-2xl bg-gradient-to-br from-purple-900/20 to-blue-900/20 ring-1 ring-purple-700/50 backdrop-blur-sm">
            <div className="flex flex-col sm:flex-row items-center justify-between gap-6">
              <div className="flex items-center gap-4">
                <LikeButton postSlug={post.slug} />
                <span className="text-gray-400">|</span>
                <SocialShareButtons 
                  url={currentUrl} 
                  title={post.title} 
                  description={post.description} 
                />
              </div>
            </div>
          </div>

          {/* Giscus Comments Section */}
          <GiscusComments postSlug={post.slug} postTitle={post.title} />

          {/* Author Bio */}
          {post.author && (
            <div className="mt-20 mb-16 p-8 rounded-2xl bg-gradient-to-br from-blue-900/20 to-green-900/20 ring-1 ring-gray-700/50 backdrop-blur-sm">
              <div className="flex items-start gap-6">
                <div className="w-16 h-16 rounded-full bg-gradient-to-br from-blue-500 to-green-500 flex items-center justify-center text-white font-bold text-xl">
                  {getAuthorInitials(post.author)}
                </div>
                <div className="flex-1">
                  <h3 className="text-xl font-bold text-white mb-2">{post.author}</h3>
                  <p className="text-blue-300 font-medium mb-3">Software Engineer | Full-Stack Developer | SEO Specialist</p>
                  <p className="text-gray-300 leading-relaxed mb-4">
                    With over 6 years of experience in software development and digital marketing, I specialize in creating 
                    high-performance web applications and implementing effective SEO strategies. Currently based in Berlin, 
                    I help businesses optimize their online presence through technical expertise and data-driven approaches.
                  </p>
                  <div className="flex flex-wrap gap-3">
                    <a 
                      href="https://ssohail.com" 
                      target="_blank" 
                      rel="noopener"
                      className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors font-medium"
                    >
                      Visit Website
                    </a>
                    <a 
                      href="https://github.com/saqibroy" 
                      target="_blank" 
                      rel="noopener"
                      className="inline-flex items-center gap-2 px-4 py-2 bg-gray-800 hover:bg-gray-700 text-white rounded-lg transition-colors font-medium ring-1 ring-gray-600"
                    >
                      GitHub
                    </a>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Call to Action */}
          <div className="mt-16 mb-20 text-center p-8 rounded-2xl bg-gradient-to-br from-purple-900/20 to-pink-900/20 ring-1 ring-purple-700/50 backdrop-blur-sm">
            <h3 className="text-2xl font-bold text-white mb-4">Found this article helpful?</h3>
            <p className="text-gray-300 mb-6 max-w-2xl mx-auto">
              Get more insights and tips delivered to your inbox. Subscribe to stay updated with the latest trends and strategies.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a 
                href="mailto:saqib@ssohail.com" 
                className="px-8 py-3 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white rounded-lg font-medium transition-all duration-300 transform hover:scale-105"
              >
                Get in Touch
              </a>
              <Link href="/blog" className="px-8 py-3 bg-gray-800 hover:bg-gray-700 text-white rounded-lg font-medium transition-colors ring-1 ring-gray-600">
                Read More Articles
              </Link>
            </div>
          </div>
        </div>
      </article>
    </Layout>
  );
}

function formatTime(seconds: number) {
  const m = Math.floor(seconds / 60)
    .toString()
    .padStart(1, "0");
  const s = Math.floor(seconds % 60)
    .toString()
    .padStart(2, "0");
  return `${m}:${s}`;
}